"""empty message
Revision ID: 526df5812a79
Revises: f0c69f273d5d
Create Date: 2018-11-01 11:13:03.485669
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '526df5812a79'
down_revision = 'f0c69f273d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE queries SET query_meta_update_ts = now()')
    op.alter_column('queries', 'query_meta_update_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(u'now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queries', 'query_meta_update_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(u'now()'))
    # ### end Alembic commands ###
