
"""Add query_meta_update_ts to queries table
Revision ID: f0c69f273d5d
Revises: d1eae8b9893e
Create Date: 2018-10-29 12:21:16.003232
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c69f273d5d'
down_revision = 'd1eae8b9893e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('query_meta_update_ts',  sa.DateTime(timezone=True)))
    op.alter_column('queries', 'query_meta_update_ts', nullable=False, server_default=sa.text(u'now()'))
  @sharmaNK

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'query_meta_update_ts')
    # ### end Alembic commands ###
